### 1. Iniciar Sesión (El backend responderá con la cookie Set-Cookie)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "laura.hernandez@gmail.com",
  "clave": "Anubis@68"
}

###

### 2. Registrar Técnico (La extensión envía la cookie de sesión automáticamente)
POST http://localhost:8080/api/user/register
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJsYXVyYS5oZXJuYW5kZXpAZ21haWwuY29tIiwiaXNzIjoiZG9taXRpbGEiLCJhdWQiOlsiZG9taXRpbGEiXSwiaWF0IjoxNzgxNzgxNzc1LCJleHAiOjE3ODE4NjgxNzV9.MZkRW4c2pkHZaejlZeYJVVqlTzC_i1A8LNL2QkqfBlqLhJL0DrZaPSgwszevNRw8

{
  "nombre": "María",
  "apellido1": "González",
  "apellido2": "Rodríguez",
  "email": "maria.gonzalez@domitila.com",
  "clave": "Password@2",
  "telefono": "633333333"
}