### 1. Iniciar Sesión (El backend responderá con la cookie Set-Cookie)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "laura.hernandez@gmail.com",
  "clave": "Anubis@68"
}

###

### 2. Registrar Técnico (La extensión envía la cookie de sesión automáticamente)
POST http://localhost:8080/api/user/register
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJsYXVyYS5oZXJuYW5kZXpAZ21haWwuY29tIiwiaXNzIjoiZG9taXRpbGEiLCJhdWQiOlsiZG9taXRpbGEiXSwiaWF0IjoxNzgxODAwNDcxLCJleHAiOjE3ODE4ODY4NzF9.AujvMvEfl5pEa6usdAYf7EwlKCTKtxcPwcSZHQVVbs93CcY9ULaOA2eVmrs41y6Y

{
  "nombre": "Carlos",
  "apellido1": "Chiqui",
  "apellido2": "Pereyra",
  "email": "carlos.chiqui@gmail.com",
  "clave": "Password@2",
  "telefono": "622222222"
}