spring.application.name=projects

# URL de la conexión a MariaDB (Puerto estándar 3306)
spring.datasource.url=jdbc:mariadb://localhost:3306/tecnicos?allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${MySQL}

# Driver oficial de MariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Estrategia de creación automática de tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# Desactiva el patrón Open Session In View para mejorar el rendimiento de la API
spring.jpa.open-in-view=false


# La clave secreta DEBE ser un texto largo codificado en Base64 de mínimo 32 caracteres
security.jwt.secret-key=3c96364b449b81aa6612c6a45749f782f9d8a391583161c5c16503c4f74d9e0d
# Tiempo de vida del token en milisegundos (86400000 ms = 24 horas)
security.jwt.expiration-time=86400000
# Emisor del token
security.jwt.issuer=domitila
# Audiencia del token
security.jwt.audience=domitila

# Apaga definitivamente el warning del InitializeUserDetailsManagerConfigurer
logging.level.org.springframework.security.config.annotation.authentication=ERROR
