# Base de datos local
spring.datasource.url=jdbc:mariadb://localhost:3306/domitila_db?allowPublicKeyRetrieval=true&connectionTimeZone=Atlantic/Canary
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Anubis@68}

# Pool local
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Desarrollo
spring.jpa.hibernate.ddl-auto=update
security.jwt.secret-key=${JWT_SECRET_KEY:3c96364b449b81aa6612c6a45749f782f9d8a391583161c5c16503c4f74d9e0d}
security.jwt.cookie-secure=false
security.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost,http://127.0.0.1,http://localhost:*,http://127.0.0.1:*}
